### ISSUE TITLE
Fallback with disabled JS

### ISSUE THREAD

**Issue by krystian3w** [Arkshine/discourse-features-test#1]
I noticed 2 of your 3 tests can be checked with blocked or interrupted[^1] JS:

```css
.feature #relative-color-result:empty,
.feature #subgrid-result:empty,
.feature #lookbehind-result:empty {
	color: var(--error-color);
	background: var(--error-bg)
}
.feature #relative-color-result:empty::before,
.feature #subgrid-result:empty::before,
.feature #lookbehind-result:empty::before {
	content: '❌ Not Supported'
}
.feature #lookbehind-result:empty::after {
	content: ' (due disabled JavaScript or blocked/aborted inline scripts)'
}

@supports (color: hsl(from green h s l)) {
	.feature #relative-color-result:empty::before {
		content: '✅ '
	}
	.feature #relative-color-result:empty::after {
		content: ' Supported'
	}
	.feature #relative-color-result:empty {
		color: hsl(from var(--success-color) h s l);
		background: hsl(from var(--success-bg) h s l)
	}
}
@supports (grid-template-rows: subgrid) {
	.feature #subgrid-result:empty::before {
		content: '✅ '
	}
	.feature #subgrid-result:empty::after {
		content: ' Supported'
	}
	.feature #subgrid-result:empty {
		color: var(--success-color);
		background: var(--success-bg)
	}
}
```

1. https://developer.mozilla.org/en-US/docs/Web/CSS/@supports#browser_compatibility
2. https://caniuse.com/css-featurequeries

<details> <summary> screenshot </summary>

![Image](https://github.com/user-attachments/assets/1bf20df0-ce9c-499f-9b31-293f8657d6d4)

</details>

With relative colours, the `@supports` syntax could be limited only to inserting text in a pseudo-element (colour and background can be done by line duplication):

```css
.feature #relative-color-result:empty {
	color: var(--error-color);
	color: hsl(from var(--success-color) h s l);
	background: var(--error-bg);
	background: hsl(from var(--success-bg) h s l)
}
```

[^1]: The only thing I haven't tried is to interrupt JavaScript with uBo/AdGuard scriptlets: <ul><li> https://github.com/gorhill/ublock/wiki/Resources-Library </li><li> https://github.com/AdguardTeam/Scriptlets#scriptlets </li></ul>

---
